version: "1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports:
      - "9000:9000"
    env_file:
      - ./.dev.env
    volumes:
      - ./:/opt/app/
    networks:
      - devnet
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - ./.dev.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - devnet
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
